 password:secret
 port:32342
 server:localhost
 user:root
 database:postgres
 source:trade
 filename:./xml/trades.xml
Source:  trade
File name:  ./xml/trades.xml
Connecting to database host=localhost port=32342 user=root password=secret dbname=postgres sslmode=disable
Successfully Opened ./xml/trades.xmlinsert into trd_trade ( trd_recordno, trd_glosstraderef, trd_versiono, trd_origin, trd_tradetype, trd_settlementstatus, trd_tradestatus, trd_originversion) values ( 148931,00000000000000138893,1,'TE','ECAG','CANC','C',2);
error pq: duplicate key value violates unique constraint "trd_settlement_pkey"error pq: duplicate key value violates unique constraint "trd_settlement_pkey"insert into trd_trade ( trd_recordno, trd_glosstraderef, trd_versiono, trd_origin, trd_tradetype, trd_settlementstatus, trd_tradestatus, trd_originversion) values ( 149933,00000000000000139892,1,'TE','ECAG','CANC','C',2);
error pq: duplicate key value violates unique constraint "trd_settlement_pkey"error pq: duplicate key value violates unique constraint "trd_settlement_pkey"insert into trd_trade ( trd_recordno, trd_glosstraderef, trd_versiono, trd_origin, trd_tradetype, trd_settlementstatus, trd_tradestatus, trd_originversion) values ( 187290,00000000000000178402,1,'TE','CAGS','NONE','N',);
insert into trd_trade ( trd_recordno, trd_glosstraderef, trd_versiono, trd_origin, trd_tradetype, trd_settlementstatus, trd_tradestatus, trd_originversion) values ( 190584,00000000000000180477,1,'BLOOMBERG','EBAG','NONE','N',1);
insert into trd_trade ( trd_recordno, trd_glosstraderef, trd_versiono, trd_origin, trd_tradetype, trd_settlementstatus, trd_tradestatus, trd_originversion) values ( 190585,00000000000000180479,1,'XMLFEED','ECAG','NONE','N',1);
insert into trd_trade ( trd_recordno, trd_glosstraderef, trd_versiono, trd_origin, trd_tradetype, trd_settlementstatus, trd_tradestatus, trd_originversion) values ( 190586,00000000000000180480,1,'XMLFEED','EBAG','NONE','N',1);
insert into trd_trade ( trd_recordno, trd_glosstraderef, trd_versiono, trd_origin, trd_tradetype, trd_settlementstatus, trd_tradestatus, trd_originversion) values ( 190588,00000000000000180482,1,'XMLFEED','ECAG','SUPC','X',1);
insert into trd_trade ( trd_recordno, trd_glosstraderef, trd_versiono, trd_origin, trd_tradetype, trd_settlementstatus, trd_tradestatus, trd_originversion) values ( 190589,00000000000000180483,1,'XMLFEED','EBAG','NONE','N',1);
insert into trd_trade ( trd_recordno, trd_glosstraderef, trd_versiono, trd_origin, trd_tradetype, trd_settlementstatus, trd_tradestatus, trd_originversion) values ( 190592,00000000000000180486,1,'XMLFEED','ECAG','NONE','N',1);
insert into trd_trade ( trd_recordno, trd_glosstraderef, trd_versiono, trd_origin, trd_tradetype, trd_settlementstatus, trd_tradestatus, trd_originversion) values ( 190593,00000000000000180487,1,'XMLFEED','EBAG','FULL','N',1);
error pq: duplicate key value violates unique constraint "trd_settlement_pkey"error pq: duplicate key value violates unique constraint "trd_settlement_pkey"insert into trd_trade ( trd_recordno, trd_glosstraderef, trd_versiono, trd_origin, trd_tradetype, trd_settlementstatus, trd_tradestatus, trd_originversion) values ( 190594,00000000000000180488,1,'XMLFEED','ECAG','NONE','N',1);
insert into trd_trade ( trd_recordno, trd_glosstraderef, trd_versiono, trd_origin, trd_tradetype, trd_settlementstatus, trd_tradestatus, trd_originversion) values ( 190595,00000000000000180489,1,'XMLFEED','EBAG','FAIL','N',1);
error pq: duplicate key value violates unique constraint "trd_settlement_pkey"error pq: duplicate key value violates unique constraint "trd_settlement_pkey"insert into trd_trade ( trd_recordno, trd_glosstraderef, trd_versiono, trd_origin, trd_tradetype, trd_settlementstatus, trd_tradestatus, trd_originversion) values ( 190596,00000000000000180490,1,'XMLPCFEED','ECAG','NONE','N',1);
insert into trd_trade ( trd_recordno, trd_glosstraderef, trd_versiono, trd_origin, trd_tradetype, trd_settlementstatus, trd_tradestatus, trd_originversion) values ( 190597,00000000000000180491,1,'XMLPCFEED','EBAG','FAIL','N',1);
error pq: duplicate key value violates unique constraint "trd_settlement_pkey"error pq: duplicate key value violates unique constraint "trd_settlement_pkey"insert into trd_trade ( trd_recordno, trd_glosstraderef, trd_versiono, trd_origin, trd_tradetype, trd_settlementstatus, trd_tradestatus, trd_originversion) values ( 190598,00000000000000180492,1,'XMLPCFEED','ECAG','NONE','N',1);
insert into trd_trade ( trd_recordno, trd_glosstraderef, trd_versiono, trd_origin, trd_tradetype, trd_settlementstatus, trd_tradestatus, trd_originversion) values ( 190599,00000000000000180493,1,'XMLPCFEED','EBAG','FAIL','N',1);
error pq: duplicate key value violates unique constraint "trd_settlement_pkey"error pq: duplicate key value violates unique constraint "trd_settlement_pkey"insert into trd_trade ( trd_recordno, trd_glosstraderef, trd_versiono, trd_origin, trd_tradetype, trd_settlementstatus, trd_tradestatus, trd_originversion) values ( 190600,00000000000000180494,1,'ULMO','ECAG','FAIL','N',1);
error pq: duplicate key value violates unique constraint "trd_settlement_pkey"error pq: duplicate key value violates unique constraint "trd_settlement_pkey"insert into trd_trade ( trd_recordno, trd_glosstraderef, trd_versiono, trd_origin, trd_tradetype, trd_settlementstatus, trd_tradestatus, trd_originversion) values ( 190601,00000000000000180495,1,'ULMO','EBAG','FULL','N',1);
error pq: duplicate key value violates unique constraint "trd_settlement_pkey"error pq: duplicate key value violates unique constraint "trd_settlement_pkey"insert into trd_trade ( trd_recordno, trd_glosstraderef, trd_versiono, trd_origin, trd_tradetype, trd_settlementstatus, trd_tradestatus, trd_originversion) values ( 190602,00000000000000180496,1,'TE','ECAG','CANC','C',2);
error pq: duplicate key value violates unique constraint "trd_settlement_pkey"error pq: duplicate key value violates unique constraint "trd_settlement_pkey"insert into trd_trade ( trd_recordno, trd_glosstraderef, trd_versiono, trd_origin, trd_tradetype, trd_settlementstatus, trd_tradestatus, trd_originversion) values ( 190603,00000000000000180497,1,'TE','EBAG','CANC','C',2);
error pq: duplicate key value violates unique constraint "trd_settlement_pkey"error pq: duplicate key value violates unique constraint "trd_settlement_pkey"insert into trd_trade ( trd_recordno, trd_glosstraderef, trd_versiono, trd_origin, trd_tradetype, trd_settlementstatus, trd_tradestatus, trd_originversion) values ( 190604,00000000000000180498,1,'ULMO','ECAG','FAIL','N',1);
error pq: duplicate key value violates unique constraint "trd_settlement_pkey"error pq: duplicate key value violates unique constraint "trd_settlement_pkey"insert into trd_trade ( trd_recordno, trd_glosstraderef, trd_versiono, trd_origin, trd_tradetype, trd_settlementstatus, trd_tradestatus, trd_originversion) values ( 190605,00000000000000180499,1,'ULMO','EBAG','FULL','N',1);
error pq: duplicate key value violates unique constraint "trd_settlement_pkey"error pq: duplicate key value violates unique constraint "trd_settlement_pkey"insert into trd_trade ( trd_recordno, trd_glosstraderef, trd_versiono, trd_origin, trd_tradetype, trd_settlementstatus, trd_tradestatus, trd_originversion) values ( 191586,00000000000000180482,2,'XMLFEED','ECAG','NONE','A',2);
insert into trd_settlement (trd_recordno, trd_deliverytype, trd_settleeventinstr, trd_settleterms, trd_originalqty,trd_openqty, trd_settledate, trd_delrecind, trd_settlestatus, trd_tradestatus, trd_settlenarrative1, trd_settlenarrative2, trd_settlenarrative3, trd_settlenarrative4,trd_settlenarrative5, trd_settlenarrative6, trd_settlenarrative7, trd_settlenarrative8, trd_dompaliaswil, trd_dompaliasdesc, trd_dompdepottypewil, trd_dompdaccwil,trd_dompservicewil, trd_secpaliaswil, trd_secpservicewil)values (148931,'PSET','6758','FOP','100010001000.000','100010001000.000','2021-07-29T00:00','R','C','C','','','','','','','','','JASD00','JASD00','COMP','JASD00','JASDEC','JASD00','JASDEC');
insert into trd_settlement (trd_recordno, trd_deliverytype, trd_settleeventinstr, trd_settleterms, trd_originalqty,trd_openqty, trd_settledate, trd_delrecind, trd_settlestatus, trd_tradestatus, trd_settlenarrative1, trd_settlenarrative2, trd_settlenarrative3, trd_settlenarrative4,trd_settlenarrative5, trd_settlenarrative6, trd_settlenarrative7, trd_settlenarrative8, trd_dompaliaswil, trd_dompaliasdesc, trd_dompdepottypewil, trd_dompdaccwil,trd_dompservicewil, trd_secpaliaswil, trd_secpservicewil)values (148931,'SSET','JPY','FOP','480748074807.000','480748074807.000','2021-07-29T00:00','D','C','C','','','','','','','','','JPY CASH','JPY CASH','COMP','JPY CASH','JASDEC','JPY CASH','JASDEC');
insert into trd_settlement (trd_recordno, trd_deliverytype, trd_settleeventinstr, trd_settleterms, trd_originalqty,trd_openqty, trd_settledate, trd_delrecind, trd_settlestatus, trd_tradestatus, trd_settlenarrative1, trd_settlenarrative2, trd_settlenarrative3, trd_settlenarrative4,trd_settlenarrative5, trd_settlenarrative6, trd_settlenarrative7, trd_settlenarrative8, trd_dompaliaswil, trd_dompaliasdesc, trd_dompdepottypewil, trd_dompdaccwil,trd_dompservicewil, trd_secpaliaswil, trd_secpservicewil)values (149933,'PSET','6758','FOP','100010001000.000','100010001000.000','2021-07-29T00:00','R','C','C','','','','','','','','','JASD00','JASD00','COMP','JASD00','JASDEC','JASD00','JASDEC');
insert into trd_settlement (trd_recordno, trd_deliverytype, trd_settleeventinstr, trd_settleterms, trd_originalqty,trd_openqty, trd_settledate, trd_delrecind, trd_settlestatus, trd_tradestatus, trd_settlenarrative1, trd_settlenarrative2, trd_settlenarrative3, trd_settlenarrative4,trd_settlenarrative5, trd_settlenarrative6, trd_settlenarrative7, trd_settlenarrative8, trd_dompaliaswil, trd_dompaliasdesc, trd_dompdepottypewil, trd_dompdaccwil,trd_dompservicewil, trd_secpaliaswil, trd_secpservicewil)values (149933,'SSET','JPY','FOP','480748074807.000','480748074807.000','2021-07-29T00:00','D','C','C','','','','','','','','','JPY CASH','JPY CASH','COMP','JPY CASH','JASDEC','JPY CASH','JASDEC');
insert into trd_settlement (trd_recordno, trd_deliverytype, trd_settleeventinstr, trd_settleterms, trd_originalqty,trd_openqty, trd_settledate, trd_delrecind, trd_settlestatus, trd_tradestatus, trd_settlenarrative1, trd_settlenarrative2, trd_settlenarrative3, trd_settlenarrative4,trd_settlenarrative5, trd_settlenarrative6, trd_settlenarrative7, trd_settlenarrative8, trd_dompaliaswil, trd_dompaliasdesc, trd_dompdepottypewil, trd_dompdaccwil,trd_dompservicewil, trd_secpaliaswil, trd_secpservicewil)values (190593,'PSET','1928','DVP','7000.000','0.000','2022-08-12T00:00','R','Y','N','','','','','','','','','JASD00','JASD00','COMP','JASD00','JASDEC','JASD00','JASDEC');
insert into trd_settlement (trd_recordno, trd_deliverytype, trd_settleeventinstr, trd_settleterms, trd_originalqty,trd_openqty, trd_settledate, trd_delrecind, trd_settlestatus, trd_tradestatus, trd_settlenarrative1, trd_settlenarrative2, trd_settlenarrative3, trd_settlenarrative4,trd_settlenarrative5, trd_settlenarrative6, trd_settlenarrative7, trd_settlenarrative8, trd_dompaliaswil, trd_dompaliasdesc, trd_dompdepottypewil, trd_dompdaccwil,trd_dompservicewil, trd_secpaliaswil, trd_secpservicewil)values (190593,'SSET','JPY','DVP','16759700.000','0.000','2022-08-12T00:00','D','Y','N','','','','','','','','','JSCC CASH','JSCC CASH','COMP','JSCC CASH','JASDEC','JSCC CASH','JASDEC');
insert into trd_settlement (trd_recordno, trd_deliverytype, trd_settleeventinstr, trd_settleterms, trd_originalqty,trd_openqty, trd_settledate, trd_delrecind, trd_settlestatus, trd_tradestatus, trd_settlenarrative1, trd_settlenarrative2, trd_settlenarrative3, trd_settlenarrative4,trd_settlenarrative5, trd_settlenarrative6, trd_settlenarrative7, trd_settlenarrative8, trd_dompaliaswil, trd_dompaliasdesc, trd_dompdepottypewil, trd_dompdaccwil,trd_dompservicewil, trd_secpaliaswil, trd_secpservicewil)values (190595,'PSET','6503','DVP','5000.000','5000.000','2022-08-12T00:00','D','N','N','','','','','','','','','JASD00','JASD00','COMP','JASD00','JASDEC','JASD00','JASDEC');
insert into trd_settlement (trd_recordno, trd_deliverytype, trd_settleeventinstr, trd_settleterms, trd_originalqty,trd_openqty, trd_settledate, trd_delrecind, trd_settlestatus, trd_tradestatus, trd_settlenarrative1, trd_settlenarrative2, trd_settlenarrative3, trd_settlenarrative4,trd_settlenarrative5, trd_settlenarrative6, trd_settlenarrative7, trd_settlenarrative8, trd_dompaliaswil, trd_dompaliasdesc, trd_dompdepottypewil, trd_dompdaccwil,trd_dompservicewil, trd_secpaliaswil, trd_secpservicewil)values (190595,'SSET','JPY','DVP','9482600.000','9482600.000','2022-08-12T00:00','R','N','N','','','','','','','','','JSCC CASH','JSCC CASH','COMP','JSCC CASH','JASDEC','JSCC CASH','JASDEC');
insert into trd_settlement (trd_recordno, trd_deliverytype, trd_settleeventinstr, trd_settleterms, trd_originalqty,trd_openqty, trd_settledate, trd_delrecind, trd_settlestatus, trd_tradestatus, trd_settlenarrative1, trd_settlenarrative2, trd_settlenarrative3, trd_settlenarrative4,trd_settlenarrative5, trd_settlenarrative6, trd_settlenarrative7, trd_settlenarrative8, trd_dompaliaswil, trd_dompaliasdesc, trd_dompdepottypewil, trd_dompdaccwil,trd_dompservicewil, trd_secpaliaswil, trd_secpservicewil)values (190597,'PSET','6503','DVP','5000.000','5000.000','2022-08-12T00:00','D','N','N','','','','','','','','','JASD00','JASD00','COMP','JASD00','JASDEC','JASD00','JASDEC');
insert into trd_settlement (trd_recordno, trd_deliverytype, trd_settleeventinstr, trd_settleterms, trd_originalqty,trd_openqty, trd_settledate, trd_delrecind, trd_settlestatus, trd_tradestatus, trd_settlenarrative1, trd_settlenarrative2, trd_settlenarrative3, trd_settlenarrative4,trd_settlenarrative5, trd_settlenarrative6, trd_settlenarrative7, trd_settlenarrative8, trd_dompaliaswil, trd_dompaliasdesc, trd_dompdepottypewil, trd_dompdaccwil,trd_dompservicewil, trd_secpaliaswil, trd_secpservicewil)values (190597,'SSET','JPY','DVP','9482600.000','9482600.000','2022-08-12T00:00','R','N','N','','','','','','','','','JSCC CASH','JSCC CASH','COMP','JSCC CASH','JASDEC','JSCC CASH','JASDEC');
insert into trd_settlement (trd_recordno, trd_deliverytype, trd_settleeventinstr, trd_settleterms, trd_originalqty,trd_openqty, trd_settledate, trd_delrecind, trd_settlestatus, trd_tradestatus, trd_settlenarrative1, trd_settlenarrative2, trd_settlenarrative3, trd_settlenarrative4,trd_settlenarrative5, trd_settlenarrative6, trd_settlenarrative7, trd_settlenarrative8, trd_dompaliaswil, trd_dompaliasdesc, trd_dompdepottypewil, trd_dompdaccwil,trd_dompservicewil, trd_secpaliaswil, trd_secpservicewil)values (190599,'PSET','6503','DVP','5000.000','5000.000','2022-08-12T00:00','D','N','N','','','','','','','','','JASD00','JASD00','COMP','JASD00','JASDEC','JASD00','JASDEC');
insert into trd_settlement (trd_recordno, trd_deliverytype, trd_settleeventinstr, trd_settleterms, trd_originalqty,trd_openqty, trd_settledate, trd_delrecind, trd_settlestatus, trd_tradestatus, trd_settlenarrative1, trd_settlenarrative2, trd_settlenarrative3, trd_settlenarrative4,trd_settlenarrative5, trd_settlenarrative6, trd_settlenarrative7, trd_settlenarrative8, trd_dompaliaswil, trd_dompaliasdesc, trd_dompdepottypewil, trd_dompdaccwil,trd_dompservicewil, trd_secpaliaswil, trd_secpservicewil)values (190599,'SSET','JPY','DVP','9482600.000','9482600.000','2022-08-12T00:00','R','N','N','','','','','','','','','JSCC CASH','JSCC CASH','COMP','JSCC CASH','JASDEC','JSCC CASH','JASDEC');
insert into trd_settlement (trd_recordno, trd_deliverytype, trd_settleeventinstr, trd_settleterms, trd_originalqty,trd_openqty, trd_settledate, trd_delrecind, trd_settlestatus, trd_tradestatus, trd_settlenarrative1, trd_settlenarrative2, trd_settlenarrative3, trd_settlenarrative4,trd_settlenarrative5, trd_settlenarrative6, trd_settlenarrative7, trd_settlenarrative8, trd_dompaliaswil, trd_dompaliasdesc, trd_dompdepottypewil, trd_dompdaccwil,trd_dompservicewil, trd_secpaliaswil, trd_secpservicewil)values (190600,'PSET','6503','DVP','5000.000','5000.000','2022-08-12T00:00','R','N','N','','','','','','','','','JASD00','JASD00','COMP','JASD00','JASDEC','JASD00','JASDEC');
insert into trd_settlement (trd_recordno, trd_deliverytype, trd_settleeventinstr, trd_settleterms, trd_originalqty,trd_openqty, trd_settledate, trd_delrecind, trd_settlestatus, trd_tradestatus, trd_settlenarrative1, trd_settlenarrative2, trd_settlenarrative3, trd_settlenarrative4,trd_settlenarrative5, trd_settlenarrative6, trd_settlenarrative7, trd_settlenarrative8, trd_dompaliaswil, trd_dompaliasdesc, trd_dompdepottypewil, trd_dompdaccwil,trd_dompservicewil, trd_secpaliaswil, trd_secpservicewil)values (190600,'SSET','JPY','DVP','9477482.000','9477482.000','2022-08-12T00:00','D','N','N','','','','','','','','','JDCC CASH','JDCC CASH','COMP','JDCC CASH','JASDEC','JDCC CASH','JASDEC');
insert into trd_settlement (trd_recordno, trd_deliverytype, trd_settleeventinstr, trd_settleterms, trd_originalqty,trd_openqty, trd_settledate, trd_delrecind, trd_settlestatus, trd_tradestatus, trd_settlenarrative1, trd_settlenarrative2, trd_settlenarrative3, trd_settlenarrative4,trd_settlenarrative5, trd_settlenarrative6, trd_settlenarrative7, trd_settlenarrative8, trd_dompaliaswil, trd_dompaliasdesc, trd_dompdepottypewil, trd_dompdaccwil,trd_dompservicewil, trd_secpaliaswil, trd_secpservicewil)values (190601,'PSET','6503','DVP','5000.000','0.000','2022-08-12T00:00','D','Y','N','','','','','','','','','JASD00','JASD00','COMP','JASD00','JASDEC','JASD00','JASDEC');
insert into trd_settlement (trd_recordno, trd_deliverytype, trd_settleeventinstr, trd_settleterms, trd_originalqty,trd_openqty, trd_settledate, trd_delrecind, trd_settlestatus, trd_tradestatus, trd_settlenarrative1, trd_settlenarrative2, trd_settlenarrative3, trd_settlenarrative4,trd_settlenarrative5, trd_settlenarrative6, trd_settlenarrative7, trd_settlenarrative8, trd_dompaliaswil, trd_dompaliasdesc, trd_dompdepottypewil, trd_dompdaccwil,trd_dompservicewil, trd_secpaliaswil, trd_secpservicewil)values (190601,'SSET','JPY','DVP','9482600.000','0.000','2022-08-12T00:00','R','Y','N','','','','','','','','','JSCC CASH','JSCC CASH','COMP','JSCC CASH','JASDEC','JSCC CASH','JASDEC');
insert into trd_settlement (trd_recordno, trd_deliverytype, trd_settleeventinstr, trd_settleterms, trd_originalqty,trd_openqty, trd_settledate, trd_delrecind, trd_settlestatus, trd_tradestatus, trd_settlenarrative1, trd_settlenarrative2, trd_settlenarrative3, trd_settlenarrative4,trd_settlenarrative5, trd_settlenarrative6, trd_settlenarrative7, trd_settlenarrative8, trd_dompaliaswil, trd_dompaliasdesc, trd_dompdepottypewil, trd_dompdaccwil,trd_dompservicewil, trd_secpaliaswil, trd_secpservicewil)values (190602,'PSET','7974','DVP','400.000','400.000','2022-08-12T00:00','D','C','C','','','','','','','','','JASD00','JASD00','COMP','JASD00','JASDEC','JASD00','JASDEC');
insert into trd_settlement (trd_recordno, trd_deliverytype, trd_settleeventinstr, trd_settleterms, trd_originalqty,trd_openqty, trd_settledate, trd_delrecind, trd_settlestatus, trd_tradestatus, trd_settlenarrative1, trd_settlenarrative2, trd_settlenarrative3, trd_settlenarrative4,trd_settlenarrative5, trd_settlenarrative6, trd_settlenarrative7, trd_settlenarrative8, trd_dompaliaswil, trd_dompaliasdesc, trd_dompdepottypewil, trd_dompdaccwil,trd_dompservicewil, trd_secpaliaswil, trd_secpservicewil)values (190602,'SSET','JPY','DVP','22831491.000','22831491.000','2022-08-12T00:00','R','C','C','','','','','','','','','JDCC CASH','JDCC CASH','COMP','JDCC CASH','JASDEC','JDCC CASH','JASDEC');
insert into trd_settlement (trd_recordno, trd_deliverytype, trd_settleeventinstr, trd_settleterms, trd_originalqty,trd_openqty, trd_settledate, trd_delrecind, trd_settlestatus, trd_tradestatus, trd_settlenarrative1, trd_settlenarrative2, trd_settlenarrative3, trd_settlenarrative4,trd_settlenarrative5, trd_settlenarrative6, trd_settlenarrative7, trd_settlenarrative8, trd_dompaliaswil, trd_dompaliasdesc, trd_dompdepottypewil, trd_dompdaccwil,trd_dompservicewil, trd_secpaliaswil, trd_secpservicewil)values (190603,'PSET','7974','DVP','400.000','400.000','2022-08-12T00:00','R','C','C','','','','','','','','','JASD00','JASD00','COMP','JASD00','JASDEC','JASD00','JASDEC');
insert into trd_settlement (trd_recordno, trd_deliverytype, trd_settleeventinstr, trd_settleterms, trd_originalqty,trd_openqty, trd_settledate, trd_delrecind, trd_settlestatus, trd_tradestatus, trd_settlenarrative1, trd_settlenarrative2, trd_settlenarrative3, trd_settlenarrative4,trd_settlenarrative5, trd_settlenarrative6, trd_settlenarrative7, trd_settlenarrative8, trd_dompaliaswil, trd_dompaliasdesc, trd_dompdepottypewil, trd_dompdaccwil,trd_dompservicewil, trd_secpaliaswil, trd_secpservicewil)values (190603,'SSET','JPY','DVP','22819170.000','22819170.000','2022-08-12T00:00','D','C','C','','','','','','','','','JSCC CASH','JSCC CASH','COMP','JSCC CASH','JASDEC','JSCC CASH','JASDEC');
insert into trd_settlement (trd_recordno, trd_deliverytype, trd_settleeventinstr, trd_settleterms, trd_originalqty,trd_openqty, trd_settledate, trd_delrecind, trd_settlestatus, trd_tradestatus, trd_settlenarrative1, trd_settlenarrative2, trd_settlenarrative3, trd_settlenarrative4,trd_settlenarrative5, trd_settlenarrative6, trd_settlenarrative7, trd_settlenarrative8, trd_dompaliaswil, trd_dompaliasdesc, trd_dompdepottypewil, trd_dompdaccwil,trd_dompservicewil, trd_secpaliaswil, trd_secpservicewil)values (190604,'PSET','7974','DVP','400.000','400.000','2022-08-12T00:00','D','N','N','','','','','','','','','JASD00','JASD00','COMP','JASD00','JASDEC','JASD00','JASDEC');
insert into trd_settlement (trd_recordno, trd_deliverytype, trd_settleeventinstr, trd_settleterms, trd_originalqty,trd_openqty, trd_settledate, trd_delrecind, trd_settlestatus, trd_tradestatus, trd_settlenarrative1, trd_settlenarrative2, trd_settlenarrative3, trd_settlenarrative4,trd_settlenarrative5, trd_settlenarrative6, trd_settlenarrative7, trd_settlenarrative8, trd_dompaliaswil, trd_dompaliasdesc, trd_dompdepottypewil, trd_dompdaccwil,trd_dompservicewil, trd_secpaliaswil, trd_secpservicewil)values (190604,'SSET','JPY','DVP','22831491.000','22831491.000','2022-08-12T00:00','R','N','N','','','','','','','','','JDCC CASH','JDCC CASH','COMP','JDCC CASH','JASDEC','JDCC CASH','JASDEC');
insert into trd_settlement (trd_recordno, trd_deliverytype, trd_settleeventinstr, trd_settleterms, trd_originalqty,trd_openqty, trd_settledate, trd_delrecind, trd_settlestatus, trd_tradestatus, trd_settlenarrative1, trd_settlenarrative2, trd_settlenarrative3, trd_settlenarrative4,trd_settlenarrative5, trd_settlenarrative6, trd_settlenarrative7, trd_settlenarrative8, trd_dompaliaswil, trd_dompaliasdesc, trd_dompdepottypewil, trd_dompdaccwil,trd_dompservicewil, trd_secpaliaswil, trd_secpservicewil)values (190605,'PSET','7974','DVP','400.000','0.000','2022-08-12T00:00','R','Y','N','','','','','','','','','JASD00','JASD00','COMP','JASD00','JASDEC','JASD00','JASDEC');
insert into trd_settlement (trd_recordno, trd_deliverytype, trd_settleeventinstr, trd_settleterms, trd_originalqty,trd_openqty, trd_settledate, trd_delrecind, trd_settlestatus, trd_tradestatus, trd_settlenarrative1, trd_settlenarrative2, trd_settlenarrative3, trd_settlenarrative4,trd_settlenarrative5, trd_settlenarrative6, trd_settlenarrative7, trd_settlenarrative8, trd_dompaliaswil, trd_dompaliasdesc, trd_dompdepottypewil, trd_dompdaccwil,trd_dompservicewil, trd_secpaliaswil, trd_secpservicewil)values (190605,'SSET','JPY','DVP','22819170.000','0.000','2022-08-12T00:00','D','Y','N','','','','','','','','','JSCC CASH','JSCC CASH','COMP','JSCC CASH','JASDEC','JSCC CASH','JASDEC');
